#!/bin/bash

DOWNLOAD_DIR=/data/DERI-DataSets/AlphaFold

export TF_FORCE_UNIFIED_MEMORY=1
export XLA_PYTHON_CLIENT_MEM_FRACTION=4.0

cd /app/alphafold

python run_alphafold.py \
   --data_dir="${DOWNLOAD_DIR}" \
   --output_dir="${OUTPUT}" \
   --fasta_paths="$1" \
   --model_preset=monomer \
   --db_preset=reduced_dbs \
   --uniref90_database_path=${DOWNLOAD_DIR}/uniref90/uniref90.fasta \
   --mgnify_database_path=${DOWNLOAD_DIR}/mgnify/mgy_clusters_2022_05.fa \
   --small_bfd_database_path=${DOWNLOAD_DIR}/small_bfd/bfd-first_non_consensus_sequences.fasta \
   --pdb70_database_path=${DOWNLOAD_DIR}/pdb70/pdb70 \
   --template_mmcif_dir=${DOWNLOAD_DIR}/pdb_mmcif/mmcif_files \
   --obsolete_pdbs_path=${DOWNLOAD_DIR}/pdb_mmcif/obsolete.dat \
   --use_precomputed_msas=False \
   --use_gpu_relax=False \
   --max_template_date=1900-01-01 \
   --random_seed=42 \
   "$@"

